print("            =")
print("           ===")
print("          =====")
print("         === ===")
print("        ===   ===")
print("       ===     ===")
print("      ===       ===")
print("     ===============")
print("    =================")
print("   ===             ===")
print("  ===               ===")
print(" =======================")
print("=========================")

#logo of my favorite band :) 
#refernce picture in the read me file. 
